name: tappyfi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  linear_progress_bar: ^1.1.1
  lottie: ^3.1.2
  shared_preferences: ^2.2.3
  step_progress_indicator: ^1.0.2
  # stream_chat_flutter: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
